on:
  push:
    branches:
      - main

name: 🚀 Deploy Gimp Volunteer Client-App

jobs:
  lint-code:
    name: Check Code Linting and Formatting
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort

      - name: Run Black
        run: black app.py

      - name: Run isort
        run: isort app.py

  preparing-for-prod-deployment:
    name: Preparing for PROD Deployment
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      # Add any necessary steps to prepare for the production deployment

  web-deploy-main-client:
    name: 🎉 Deploy to Production Environment
    runs-on: ubuntu-latest
    needs: preparing-for-prod-deployment
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: joyyeb.com
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: /gimp_volunteer/prod/client/
